// <auto-generated />
namespace angrybirds_iago.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ILists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ILists));
        
        string IMigrationMetadata.Id
        {
            get { return "201803160807045_ILists"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
